require: rubocop-rspec
AllCops:
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'bin/*'
    - 'config/deploy.rb'

Rails:
  Enabled: true

Rails/FilePath:
  Exclude:
    - 'config/environments/development.rb'

Metrics/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false
